### ISSUE TITLE
can only use 16 lower bits for requestCode

### ISSUE THREAD

**Issue by cinder92** [taessina/react-native-paypal-wrapper#11]
Hello, thanks for your plugin, im testing on genymotion device, Android 5.0

after clicking on a button im receiving this error, then app crash, is necessary to user have installed PayPal app for this? (on iOS just appearing a webview)

![captura de pantalla 2018-02-19 a la s 15 01 57](https://user-images.githubusercontent.com/4725556/36396895-daaefbb4-1585-11e8-83bd-6219fc9a4f33.jpg)

thanks

**Comment by cinder92** [comment]
thanks i just change the number in native module, then it works

**Comment by parmeet9891** [comment]
@cinder92 can you share exactly where u changed code, i'm getting the same error.

**Comment by cinder92** [comment]
@parmeet9891 in `RNPaypalWrapperModule.java` in line `36` i change by this number `65535`, i hep it helps

**Comment by parmeet9891** [comment]
@cinder92 yes it worked! Can you explain what this number signifies?

**Comment by cinder92** [comment]
@parmeet9891 a biiiiiiig luck hahah

**Comment by parmeet9891** [comment]
Haha, yeah @cinder92

**Comment by alvinthen** [comment]
Thanks for the contribution, I have published the fix.
