### ISSUE TITLE
Cannot read property 'initialize' of undefined ???

### ISSUE THREAD

**Issue by aditya-rumbleon** [taessina/react-native-paypal-wrapper#14]
![screen shot 2018-07-11 at 5 15 12 pm](https://user-images.githubusercontent.com/39170134/42602205-1ddf59e8-852e-11e8-8303-28c3d26f3482.png)

Any idea how to fix this issue?

**Comment by aditya-rumbleon** [comment]
Fixed it

**Comment by Talkwondo** [comment]
Please Explain how?

**Comment by addu1** [comment]
@aditya-rumbleon  How did you solve this?
