### ISSUE TITLE
after installation when i run it shows error given below

### ISSUE THREAD

**Issue by yogeshmoradiya121** [taessina/react-native-paypal-wrapper#2]
![capture](https://cloud.githubusercontent.com/assets/27858885/25692076/a1b84020-30bd-11e7-9939-6004ced9f974.PNG)
![capture](https://cloud.githubusercontent.com/assets/27858885/25692004/36835c90-30bd-11e7-86f0-7f18b8eb861f.PNG)

**Comment by alvinthen** [comment]
Hi, thanks for reporting. However this repo is not under maintenance.

The error looks like Windows-specific, permission issues?

**Comment by alvinthen** [comment]
Closing this issue, feel free to reopen if still applicable
