### ISSUE TITLE
Error:Execution failed for task ':react-native-paypal-wrapper:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by bwoodlt** [taessina/react-native-paypal-wrapper#6]
I'm unable to use the wrapper in Android. iOS works just fine but getting this error in android when I run the application:

Error:Execution failed for task ':react-native-paypal-wrapper:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

Any thoughts how to navigate this issue?

**Comment by alvinthen** [comment]
Can you provide the error output?

**Comment by bwoodlt** [comment]
@alvinthen thanks for the prompt response.

Here's the log:

:react-native-paypal-wrapper:generateDebugBuildConfig UP-TO-DATE
:react-native-paypal-wrapper:prepareLintJar UP-TO-DATE
:react-native-paypal-wrapper:generateDebugSources UP-TO-DATE
:react-native-paypal-wrapper:javaPreCompileDebug UP-TO-DATE
:react-native-paypal-wrapper:compileDebugJavaWithJavac
/Users/kunleadetayo1/Workspace/JFF/FaithCircle/node_modules/react-native-paypal-wrapper/android/src/main/java/com/taessina/paypal/RNPaypalWrapperPackage.java:19: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /Users/kunleadetayo1/Workspace/JFF/FaithCircle/node_modules/react-native-paypal-wrapper/android/src/main/java/com/taessina/paypal/RNPaypalWrapperModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

 FAILED
:app:buildInfoGeneratorDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-paypal-wrapper:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

194 actionable tasks: 3 executed, 191 up-to-date

**Comment by alvinthen** [comment]
I've released a fix, the latest version (1.2.0)

**Comment by bwoodlt** [comment]
@alvinthen Thanks a bunch! That fixed it!
